services:
  postgres:
      image: postgres
      container_name: postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: banque
        POSTGRES_PASSWORD: banque123
        POSTGRES_DB: banck_db
      networks:
        - app-network


  backend:
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "8082:8080"
    networks:
      - app-network
  waha:
    image: devlikeapro/waha
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
